name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build binary
      env:
        GOOS: linux
        GOARCH: ${{ matrix.goarch }}
      run: |
          go build -o waybar-hyprmon-widget-linux-${{ matrix.goarch }} .

    - name: Upload Release Asset
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} ./waybar-hyprmon-widget-${{ matrix.goarch }}